frr version 9.1
frr defaults traditional
hostname LER_Ingress
log syslog informational
!
interface leri-tx1
 ip address 10.0.1.1/30
!
interface leri-tx2
 ip address 10.0.2.1/30
!
interface leri-tx3
 ip address 10.0.3.1/30
!
interface leri-cr1
 ip address 10.1.3.1/30
!
interface leri-cr2
 ip address 10.1.4.1/30
!
interface leri-cr3
 ip address 10.1.5.1/30
!
! Rx1 (10.2.1.0/24): primary CR1, backup CR2, CR3
ip route 10.2.1.0/24 10.1.3.2 1
ip route 10.2.1.0/24 10.1.4.2 2
ip route 10.2.1.0/24 10.1.5.2 3
! Rx2 (10.2.2.0/24): primary CR2, backup CR3, CR1
ip route 10.2.2.0/24 10.1.4.2 1
ip route 10.2.2.0/24 10.1.5.2 2
ip route 10.2.2.0/24 10.1.3.2 3
! Rx3 (10.2.3.0/24): primary CR3, backup CR2, CR1
ip route 10.2.3.0/24 10.1.5.2 1
ip route 10.2.3.0/24 10.1.4.2 2
ip route 10.2.3.0/24 10.1.3.2 3
!
! MPLS static LSP - ingress (FEC → label push)
! Tunnel 1: Rx1(10.2.1.2) → push 100 via CoreRouter1
ip route 10.2.1.2/32 10.1.3.2 label 100
! Tunnel 2: Rx2(10.2.2.2) → push 200 via CoreRouter2
ip route 10.2.2.2/32 10.1.4.2 label 200
! Tunnel 3: Rx3(10.2.3.2) → push 300 via CoreRouter2
ip route 10.2.3.2/32 10.1.4.2 label 300
!
line vty
!
